name: build

on:
  push:
    tags: '*'
  workflow_dispatch:

jobs:
  build-release:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            publishRID: linux-x64
          - os: windows-latest
            publishRID: win-x64    
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Publish for ${{ matrix.os }}
      run: dotnet publish -c Release -r ${{ matrix.publishRID }} -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained=true
      
    - name: Upload Release Asset
      uses: xresloader/upload-to-github-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "ClientLauncher/bin/Release/net5.0/${{ matrix.publishRID }}/publish/ClientLauncher*;ClientLauncher/bin/Release/net5.0/${{ matrix.publishRID }}/publish/*.dll;ClientLauncher/bin/Release/net5.0/${{ matrix.publishRID }}/publish/*.so"
        draft: false
