name: build

on:
  push:
    tags: '*'
  workflow_dispatch:

jobs:
  build-release:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            publishRID: linux-x64
          - os: windows-latest
            publishRID: win-x64    
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: "./ClientLauncher"
    
    - name: Publish Release configuration for ${{ matrix.os }} 
      run: dotnet publish -c Release -r ${{ matrix.publishRID }} -p:PublishSingleFile=true --self-contained=true -p:IncludeNativeLibrariesForSelfExtract=true
      working-directory: "./ClientLauncher"
      
    - name: Publish Debug configuration for ${{ matrix.os }}
      run: dotnet publish -c Debug -r ${{ matrix.publishRID }} -p:PublishSingleFile=true --self-contained=true -p:IncludeNativeLibrariesForSelfExtract=true
      working-directory: "./ClientLauncher"
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          "ClientLauncher/bin/Release/net5.0/${{ matrix.publishRID }}/publish/ClientLauncher*"
          "ClientLauncher/bin/Debug/net5.0/${{ matrix.publishRID }}/publish/ClientLauncher*"
